version: "3"

services:
    geth:
        container_name: geth
        image: ethereum/client-go:v1.10.3
        volumes: 
            - ./geth_data:/geth_data
            - ./init-script.sh:/root/init-script.sh
        ports:
            - "8545:8545"
            - "30303:30303"
        command: --datadir /geth_data/data --networkid 15 --password /geth_data/data/password --unlock 0xb2942de361B73f639B3419DFb57E9fe7c503dd7f --mine --http --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "*" --allow-insecure-unlock
    geth_explorer:
        container_name: geth_explorer
        image: a5768549/geth_explorer
        ports:
            - "8000:8000"